codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 90..100
  round: down
  precision: 2
  status:
    project:
      default: off
      unit:
        flags: unit

flags:
  unit:
    paths:
      - terminus-ui/

ignore:
  - "coverage"
  - "dist"
  - "build"
  - "docs"
  # TODO: Remove 'integration' from this list when enabling integration tests
  - "integration"
  - "node_modules"
  - "out-tsc"
  - "demo/app"
  - "tooling"
  - "terminus-ui/src/**/*.spec.ts"
  - "terminus-ui/src/**/*.mock.ts"

