codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 90..100
  round: down
  precision: 2
  status:
    project:
      default: off
      unit:
        flags: unit
      integration:
        # TODO: What should this target be for integration tests?
        target: 50%
        flags: integration

flags:
  unit:
    paths:
      - src/lib/src/
  integration:
    paths:
      - integration/

ignore:
  - "coverage"
  - "dist"
  - "build"
  - "docs"
  # TODO: Remove 'integration' from this list when enabling integration tests
  - "integration"
  - "node_modules"
  - "out-tsc"
  - "src/demo"
  - "styleguide"
  - "tooling"
  - "src/lib/src/**/*.spec.ts"
  - "src/lib/src/**/*.mock.ts"

