---
engines:
  tslint:
    enabled: true
    channel: beta
  scss-lint:
    enabled: true
  #sasslint:
    #enabled: true
ratings:
  paths:
  - "src/lib/**"
exclude_paths:
  - coverage/
  - docs/
  - integration/
  - node_modules/
  - src/demo/
  - styleguide/
  - tooling/
  - out-tsc/
  - README.md
  - LICENSE
