codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 90..100
  round: down
  precision: 2

ignore:
  - "coverage"
  - "dist"
  - "build"
  - "docs"
  - "integration"
  - "node_modules"
  - "out-tsc"
  - "src/demo"
  - "styleguide"
  - "tooling"
  - "src/lib/src/**/*.spec.ts"
  - "src/lib/src/**/*.mock.ts"

