version: 2

jobs:
  build:

    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/ci-build

    environment:
      TEST_REPORTS: /coverage

    steps:
      - add_ssh_keys

      - checkout

      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn

      - run:
          name: Install Dependencies
          command: tooling/ci/install-dependencies.sh

      - save_cache:
          name: Save Yarn Cache
          key: yarn
          paths:
            - ./node_modules

      - run:
          name: Lint Styles
          command: tooling/ci/lint-scss.sh

      - run:
          name: Lint TypeScript
          command: tooling/ci/lint-typescript.sh

      - run:
          name: Run Tests
          command: tooling/ci/test-unit.sh

      - run:
          name: Build Project
          command: yarn run build

      - run:
          name: Release Test
          command: yarn run semantic-release --dry-run

      - run:
          name: Release
          command: yarn run semantic-release

      - store_artifacts:
          path: coverage/
          destination: ~/coverage/

      - store_artifacts:
          path: dist/
          destination: ~/dist/

      - store_artifacts:
          path: /home/circleci/.npm/_logs/
          destination: ~/npm_logs/




# HACK: This will allow tags to kick off the deploy process. Correct syntax support is coming soon:
# https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/8
deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"

