version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/aws-s3
  aws-s3: circleci/aws-s3@1.0.11
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1.16.1

#
# Reusable definitions
#
references:
  # Basic defaults that most jobs will need.
  defaults: &defaults
    working_directory: ~/ci-build
    docker:
      - image: circleci/node:12.16.1
      - image: cypress/base:10
    environment:
      TEST_REPORTS: /coverage

  # Filter to run a job on builds for the release branch only.
  filter_only_release_branch: &filter_only_release_branch
    filters:
      branches:
        only:
          - /^release$/

  # Filter to run a job on tagged releases.
  # https://circleci.com/docs/2.0/workflows/#using-regular-expressions-to-filter-tags-and-branches
  # https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
  release_tag_filter: &release_tag_filter
    filters:
      tags:
        only: /^v[0-9.]+.*/
      branches:
        ignore: /.*/

  # Attach the root workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: '.'


#
# Jobs
#
jobs:
  setup:
    <<: *defaults
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-release
            - yarn-packages-
            - cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive
      - run:
          name: Versions
          command: |
            echo "Yarn version: "
            yarn --version
            npx ng --version
      - save_cache:
          name: Save Yarn Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save Cypress Cache
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/Cypress
      - run:
          name: Look at Path
          command: |
            ls -al ~/
            ls -al ~/ci-build
            cp -rf ~/.cache/Cypress ~/ci-build
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          name: Look at Path after persiste to workspace
          command: |
            ls -al ~/.cache
            ls -al ~/.cache/yarn
            ls -al ~/ci-build
  #      - run:
  #          # make sure app has been installed and built
  #          # before running tests across multiple machines
  #          # this avoids installing same dependencies 10 times
  #          parallel: true # split all specs across machines
  #          parallelism: 4 # use 4 CircleCI machines to finish quickly
  #          group: 'all tests' # name this group "all tests" on the dashboard
  #          start: 'yarn run start:app' # start server before running tests
  #          wait-on: 'http://localhost:4200'
  #          command: tooling/ci/check-demo-up-and-running.sh
  #      - run:
  #          name: Cypress run
  #          command: yarn run e2e
  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive
      - run:
          name: Look at Path before build executed
          command: |
            ls -al ~/.cache
            ls -al ~/ci-build
      #      - run:
      #          name: Copy ci-build
      #          command: |
      #            cp -fr ~/ci-build/ci-build ~/
      #      - restore_cache:
      #          name: Restore Cypress Cache
      #          keys:
      #            - cache-{{ checksum "package.json" }}
      - run:
          name: Build Project
          command: yarn run build
      - run:
          name: Rename Primary Typings File
          command: tooling/ci/rename-typings-index.sh
      - store_artifacts:
          path: /home/circleci/.npm/_logs/
          destination: ~/npm_logs/
      - persist_to_workspace:
          root: .
          paths:
            - ./dist/library/*
            - .
      - run:
          name: Look at Path after build
          command: |
            ls -al ~/.cache
            ls -al ~/ci-build
  integration_test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: check workspace
          command: |
            ls -al /home/circleci
            ls -al /home/circleci/ci-build/tooling
      #      - run:
      #          name: Copy ci-build
      #          command: |
      #            cp -fr ~/ci-build/ci-build ~/
      - restore_cache:
          name: Restore Cypress Cache
          keys:
            - cache-{{ checksum "package.json" }}
      - run:
          name: Look at cache folder
          command: |
            ls -al ~/.cache
      - run:
          name: Install packages
          command: tooling/ci/check-demo-up-and-running.sh
      - run:
          # make sure app has been installed and built
          # before running tests across multiple machines
          # this avoids installing same dependencies 10 times
          # record: true # record results on Cypress Dashboard
          #          parallel: true # split all specs across machines
          #          parallelism: 4 # use 4 CircleCI machines to finish quickly
          #          group: 'all tests' # name this group "all tests" on the dashboard
          #          command: yarn start:app # start server before running tests
          command: yarn run cy:test
  #          background: true
  #      - run:
  #          name: Cypress run
  #          command: yarn run e2e
  deploy_demos:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Publish Demos
          command: tooling/ci/demos-deploy-ci.sh

#
# Workflows
#
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - integration_test:
          requires:
            - build
