version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/aws-s3
  aws-s3: circleci/aws-s3@1.0.11

#
# Reusable definitions
#
references:
  # Basic defaults that most jobs will need.
  defaults: &defaults
    working_directory: ~/ci-build
    docker:
      - image: circleci/node:12.9.1
    environment:
      TEST_REPORTS: /coverage

  # Filter to run a job on builds for the release branch only.
  filter_only_release_branch: &filter_only_release_branch
    filters:
      branches:
        only:
          - /^release$/

  # Filter to run a job on tagged releases.
  # https://circleci.com/docs/2.0/workflows/#using-regular-expressions-to-filter-tags-and-branches
  # https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
  release_tag_filter: &release_tag_filter
    filters:
      tags:
        only: /^v[0-9.]+.*/
      branches:
        ignore: /.*/

  # Attach the root workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: '.'


#
# Jobs
#
jobs:
  setup:
    <<: *defaults
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - terminusui-yarn-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - terminusui-yarn-deps-{{ .Branch }}
            - terminusui-yarn-deps-release
            - terminusui-yarn-deps-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive
      - run:
          name: Versions
          command: |
            echo "Yarn version: "
            yarn --version
            npx ng --version
      - save_cache:
          name: Save Yarn Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Lint
          command: yarn run lint:ci
  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run Tests
          command: tooling/ci/test-unit.sh
      - store_test_results:
          path: coverage/junit/
      - store_artifacts:
          path: coverage/
          destination: ~/coverage/
  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build Project
          command: yarn run build
      - run:
          name: Rename Primary Typings File
          command: tooling/ci/rename-typings-index.sh
      - store_artifacts:
          path: /home/circleci/.npm/_logs/
          destination: ~/npm_logs/
      - persist_to_workspace:
          root: .
          paths:
            - ./dist/terminus-ui/*
  publish_library:
    <<: *defaults
    steps:
      - *attach_workspace
      - add_ssh_keys
      - run:
          name: Publish Library
          command: npx semantic-release
  build_demos:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build Demos with AoT
          command: tooling/ci/build-demos-aot.sh
      - run:
          name: Update Package Versions for Demo Build
          command: tooling/ci/inject-library-version-number.sh
      - store_artifacts:
          path: /home/circleci/ci-build/dist/app/
          destination: ~/demo/
      - persist_to_workspace:
          root: .
          paths:
            - ./dist/app/*
  deploy_demos:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Publish Demos
          command: tooling/ci/demos-deploy-ci.sh
  generate_docs:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Generate Documentation
          command: yarn run docs:ci
      - run:
          name: Install emoji tool
          command: yarn global add emojis
      - run:
          name: Replace emoji codes
          command: node tooling/ci/replace-docs-emoji.js
      - persist_to_workspace:
          root: .
          paths:
            - ./docs/*
  deploy_docs:
    <<: *defaults
    steps:
      - *attach_workspace
      - aws-s3/sync:
          from: docs
          to: 's3://uilibrary-docs.terminus.ninja/"${CIRCLE_BRANCH}"'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --delete
          overwrite: true


#
# Workflows
#
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build_demos:
          requires:
            - build
      - publish_library:
          <<: *filter_only_release_branch
          requires:
            - build
            - build_demos
            - lint
            - test
      - generate_docs:
          <<: *filter_only_release_branch
          requires:
            - publish_library
      - deploy_docs:
          <<: *filter_only_release_branch
          requires:
            - generate_docs
      - deploy_demos:
          <<: *filter_only_release_branch
          requires:
            - build_demos
            - publish_library
