name: Label Approved PRs

on: [pull_request_review]

jobs:
  trigger-label:
    runs-on: ubuntu-latest
    
    steps:
    - name: Label approved pull requests
      uses: pullreminders/label-when-approved-action@v1.0.3
      with:
        secrets = ["GITHUB_TOKEN"]
        env = {
          LABEL_NAME = "Status: ready to merge"
          APPROVALS  = "2"
        }
